name = "quanthub-proxy"
main = "cloudflare-worker-v3.js"
compatibility_date = "2024-01-01"
account_id = "20e7b178f91a4ca92328922dd22abdf2"

[vars]
GITHUB_OWNER  = "krausshauss"
GITHUB_REPO   = "quahthub-dashboard"
GITHUB_BRANCH = "main"

[env.dev]
name = "quanthub-proxy-dev"

[env.dev.vars]
GITHUB_OWNER  = "krausshauss"
GITHUB_REPO   = "quanthub-dashboard-dev"
GITHUB_BRANCH = "dev"
